/**
 * Created by ewong on 5/20/2020.
 */

public with sharing class ContractAmender {/*
    public CPQ_ApiDataModels.QuoteModel load(String contractId){
        CPQ_ApiDataModels.QuoteModel quote = CPQ_ApiWrapper.amendContract(contractId);
                //SBQQ.ServiceRouter.load('SBQQ.ContractManipulationAPI.ContractAmender', contractId, null);
//        System.debug('eddie inside quoteJSON' + quoteJSON);
        return (CPQ_ApiDataModels.QuoteModel) JSON.deserialize(quoteJSON, CPQ_ApiDataModels.QuoteModel.class);
    }*/
}