/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_Apttus_Proposal_Proposal_Lina4ETest
{
    @IsTest
    private static void testTrigger()
    {
        // Force the dlrs_Apttus_Proposal_Proposal_a4ETrigger to be invoked, fails the test if org config or other Apex code prevents this.
        dlrs.RollupService.testHandler(new Apttus_Proposal__Proposal_Line_Item__c());
    }
}