/*
Main wrapper Class used in Lithium Search Controller
Developed By:- Grazitti Interactive
*/
public class LData_WrapperMain{
        public  String art_endpoint{get;set;}
        public  String title{get;set;}
        public  String created_date{get;set;}
        public  String author{get;set;}
        public  String view_author{get;set;}
        public  String description{get;set;}
        public  String board_id{get;set;}
        public  String board_endpoint{get;set;}
        public  String category{get;set;}
        
    }