public class StaticVariables {

    public static List<CampaignMember> leadCampaignMemberToUpdateUTM;
    public static List<CampaignMember> contactCampaignMemberToUpdateUTM;
    public static Boolean updatedKnowledgeVersion; //Sergio Flores 08/07/2020 W-005880
    public static Boolean leadConverted = false; //Sergio Flores 11/09/2020 W-006418
    public static Map<Id,User> userMap; //Sergio Flores 11/17/2020 W-006732
    public static List<Territory_Mapping__mdt> fields; //Sergio Flores 11/17/2020 W-006732
    public static String usrProfileName; //Sergio Flores 11/17/2020 W-006732
    public static Map<Id,Opportunity> mapOpp; //Sergio Flores 11/17/2020 W-006732
    public static Boolean ecurConverted; //SF 11/30/2020 W-006786
    public static Set<Id> closedOpportunityIds; //Name: Chris Salgado Date: 1/14/21 Purpose: W-006923

}